imports:
    - { resource: tables.yml }
services:
    dmzx.milestones.admin.controller:
        class: dmzx\milestones\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@language'
            - '%tables.milestones_table%'
    dmzx.milestones.listener:
        class: dmzx\milestones\event\listener
        arguments:
            - '@template'
            - '@dbal.conn'
            - '@language'
            - '%tables.milestones_table%'
        tags:
            - { name: event.listener }
